config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tournaments
  resources :fixtures
  resources :galleries

   root 'admin#index'

end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
  belongs_to :tournament
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :tournament
  has_many :gallery_images, dependent: :destroy
  accepts_nested_attributes_for :gallery_images, allow_destroy: :true
end

app/models/gallery_image.rb
include S3ImageConfig
class GalleryImage < ActiveRecord::Base
  belongs_to :gallery

  has_attached_file :photo,
                styles: {
                  gallery_thumb: '100x100#',
                  gallery_large: '400x400#',
                  gallery_small: '215x215#'
                },
                storage: :s3,
                url: ':s3_domain_url',
                s3_protocol: 'http',
                path: '/images/gallery_images/:id/:style.:extension',
                s3_headers: s3_headers,
                s3_credentials: s3_credentials

  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
	has_many :fixtures, dependent: :destroy
	has_one :gallery, dependent: :destroy
	has_many :gallery_images, :through => :gallery, dependent: :destroy

	# Validations
    validates :name, presence: { message: 'Add Tournament Name' }
    validates :tourn_location, presence: { message: 'Add Tournament Location' }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
before_action :authenticate_user!
def index
  @fixtures = Fixture.order('fixtures.fixture_date DESC, fixtures.kickoff_time DESC')
  @tournament_fixture = @fixtures.group_by(&:tournament)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
	before_action :authenticate_user!

  def index
    @fixtures = Fixture.all
    @tournament_fixture = @fixtures.group_by(&:tournament)
  end

  def new
    @fixture = Fixture.new
  end

  def create
    @fixture = Fixture.new(fixture_params)
    if @fixture.save
      redirect_to root_path, flash: { success: 'Fixture Successfully Created' }
    else
      render action: 'new'
    end
  end


  def edit
    @fixture = Fixture.find(params[:id])
  end

  def update
    @fixture = Fixture.find(params[:id])
    if @fixture.update_attributes(fixture_params)
      redirect_to root_path, flash: { success: 'Successfully updated Fixture' }
    else
      render action: 'edit'
    end
  end

  def destroy
    @fixture = Fixture.find(params[:id])
    @fixture.destroy
    redirect_to root_path, flash: { success: 'Successfully Destroyed Fixture' }
  end

  def show
    @fixture = Fixture.find(params[:id])
  end


  private

  def fixture_params
    params.require(:fixture).permit(:id, :home_team, :away_team, :kickoff_time, :home_score_result, :away_score_result, :fixture_date, :tournament_id)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
	before_action :authenticate_user!

  def index
    @galleries = Gallery.all
    @tournaments = Tournament.all
    @tour_gal_img = @galleries.group_by(&:tournament)
  end

  def new
    @gallery = Gallery.new
    @gallery.gallery_images.build
  end

  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      redirect_to root_path, flash: { success: 'Gallery Successfully Created' }
    else
      render action: 'new'
    end
  end


  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:id])
    if @gallery.update_attributes(gallery_params)
      redirect_to root_path, flash: { success: 'Successfully updated Gallery' }
    else
      render action: 'edit'
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
    redirect_to root_path, flash: { success: 'Successfully Destroyed Gallery' }
  end

  def show
    @gallery = Gallery.find(params[:id])
  end


  private

  def gallery_params
    params.require(:gallery).permit(:id, :tournament_id, gallery_images_attributes: [:id, :gallery_id, :photo, :_destroy])
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authenticate_user!
  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tourn_params)
    if @tournament.save
      redirect_to root_path, flash: { success: 'Tournament Successfully Created' }
    else
      render action: 'new'
    end
  end


  def edit
    @tournament = Tournament.find(params[:id])
  end

  def update
    @tournament = Tournament.find(params[:id])
    if @tournament.update_attributes(tourn_params)
      redirect_to root_path, flash: { success: 'Successfully updated Tournament' }
    else
      render action: 'edit'
    end
  end

  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy
    redirect_to root_path, flash: { success: 'Successfully Destroyed Tournament' }
  end

  def show
    @tournament = Tournament.find(params[:id])
  end

  def index
    @tournaments = Tournament.all
  end

  private

  def tourn_params
    params.require(:tournament).permit(:id, :name, :tourn_date, :tourn_location)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def date_output(date)
    date.strftime('%e %B %Y') if date
  end

  def time_output(time)
    time.strftime('%H:%M') if time
  end

  def flash_class(level)
    case level
        when 'notice' then "alert alert-info"
        when 'success' then "alert alert-success"
        when 'error' then "alert alert-error"
        when 'alert' then "alert alert-error"
    end
  end
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/admin/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 well">
      <h3>Fixtures & Results</h3>
      <% @tournament_fixture.sort.each do |tournament, fixture| %>
        <table class="table section-body">
            <thead>
              <% if tournament %>
              <h3 class="tournament-header"><%= tournament.name %> <%= date_output(tournament.tourn_date) %>
              <% end %>
              <span class="toggle"></span>
            </h3>
                <tr>
                  <th>Home Team</th>
                  <th>Away Team</th>
                  <th>Fixture Date</th>
                  <th>Kick Off</th>
                  <th>Result</th>
                  <th>Options</th>
                </tr>
            </thead>
            <tbody>
              <% fixture.each do |f| %>
                <tr>
                  <td><%= f.home_team %></td>
                  <td><%= f.away_team %></td>
                  <td><%= date_output(f.fixture_date) %></td>
                  <td><%= time_output(f.kickoff_time) %></td>
                    <% if f.home_score_result && f.away_score_result %>
                      <td><%= f.home_score_result %> - <%= f.away_score_result  %></td>
                    <% else %>
                  <td> Pending</td>
                    <% end %>
                  <td><%= link_to 'View', fixture_path(f), class: 'btn btn-success' %> <%= link_to 'Edit', edit_fixture_path(f), class: 'btn btn-warning' %> <%= link_to 'Delete', fixture_path(f.id), method: :delete,  :confirm => "Are you sure you want to delete this Fixture?", class: 'btn btn-danger' %></td>
                </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
      
    </div><!--/well-->
  </div>
</div>

app/views/fixtures/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 well">
    	<%= form_for @fixture, html: { multipart: true }  do |f| %>
        <fieldset>
        <!-- Form Name -->
        <legend>Edit Fixture</legend>
             <div class="form-group">
               <%= f.label :tournament_id  %>
               <%= f.collection_select :tournament_id, Tournament.all, :id, :name, { :prompt => "Please Select a Tournament" }, { class: 'form-control' } %>
             </div>

			<!-- Text input-->
			<div class="form-group">
			  <%= f.label :home_team %>
			  <%= f.text_field :home_team, class: 'form-control', placeholder: 'Home Team' %>
			</div>

           
			<div class="form-group">
        <%= f.label :away_team %>
			  <%= f.text_field :away_team, class: 'form-control', placeholder: 'Away Team' %>
			</div>

      <div class="form-group">
        <%= f.label :fixture_date %>
        <%= f.date_select :fixture_date, :order => [:day, :month, :year], :include_blank => true %> 
      </div>

			<div class="form-group">
        <%= f.label :kickoff_time %>
			  <%= f.time_select :kickoff_time, class: 'form-control' %>
			</div>

      <div class="form-group">
        <%= f.label 'Home Team Result'%>
        <%= f.number_field :home_score_result, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label 'Away Team Result' %>
        <%= f.number_field :away_score_result, class: 'form-control' %>
      </div>

            
      <div class="form-group">
			  <%= f.submit 'Submit', :class => 'btn btn-success' %>
			</div>

          </fieldset>
        <% end %>
      </div>
     </div>
    </div>

app/views/fixtures/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 well">
      <h3>Fixtures</h3>
      <% @tournament_fixture.sort.each do |tournament, fixture| %>
        <table class="table section-body">
            <thead>
              <h3 class="tournament-header"><%= tournament.name %> <%= date_output(tournament.tourn_date) %>
              <span class="toggle"></span>
            </h3>
                <tr>
                  <th>Home Team</th>
                  <th>Away Team</th>
                  <th>Fixture Date</th>
                  <th>Kick Off</th>
                  <th>Result</th>
                  <th>Options</th>
                </tr>
            </thead>
            <tbody>
              <% fixture.each do |f| %>
                <tr>
                  <td><%= f.home_team %></td>
                  <td><%= f.away_team %></td>
                  <td><%= date_output(f.fixture_date) %></td>
                  <td><%= time_output(f.kickoff_time) %></td>
                    <% if f.home_score_result && f.away_score_result %>
                      <td><%= f.home_score_result %> - <%= f.away_score_result  %></td>
                    <% else %>
                  <td> Pending</td>
                    <% end %>
                  <td><%= link_to 'View', fixture_path(f), class: 'btn btn-success' %> <%= link_to 'Edit', edit_fixture_path(f), class: 'btn btn-warning' %> <%= link_to 'Delete', fixture_path(f.id), method: :delete,  :confirm => "Are you sure you want to delete this Fixture?", class: 'btn btn-danger' %></td>
                </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
      
    </div><!--/well-->
  </div>
</div>

app/views/fixtures/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 well">
    	<%= form_for @fixture, html: { multipart: true }  do |f| %>
        <fieldset>
        <!-- Form Name -->
        <legend>Create New Fixture</legend>
             <div class="form-group">
               <%= f.label :tournament_id  %>
               <%= f.collection_select :tournament_id, Tournament.all, :id, :name, { :prompt => "Please Select a Tournament" }, { class: 'form-control' } %>
             </div>

			<!-- Text input-->
			<div class="form-group">
			  <%= f.label :home_team %>
			  <%= f.text_field :home_team, class: 'form-control', placeholder: 'Home Team' %>
			</div>

           
			<div class="form-group">
              <%= f.label :away_team %>
			  <%= f.text_field :away_team, class: 'form-control', placeholder: 'Away Team' %>
			</div>

      <div class="form-group">
        <%= f.label :fixture_date %>
        <%= f.date_select :fixture_date, :order => [:day, :month, :year],  :include_blank => true %> 
      </div>


			<div class="form-group">
              <%= f.label :kickoff_time %>
			  <%= f.time_select :kickoff_time, class: 'form-control' %>
			</div>
            
            <div class="form-group">
			  <%= f.submit 'Submit', :class => 'btn btn-success' %>
			</div>

          </fieldset>
        <% end %>
      </div>
     </div>
    </div>

app/views/galleries/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 well">
    	<%= nested_form_for @gallery, html: { multipart: true }  do |f| %>
        <fieldset>
        <!-- Form Name -->
        <legend>Edit Gallery</legend>
        
        <div class="form-group">
          <%= f.label :tournament_id  %>
          <%= f.collection_select :tournament_id, Tournament.all, :id, :name, { :prompt => "Please Select a Tournament" }, { class: 'form-control' } %>
        </div>

        <%= f.fields_for :gallery_images do |build| %>

        <div class="form-group">
          <% if build.object.photo? %>
            <%= build.label :photo  %><br>
            <%= image_tag build.object.photo.url :gallery_thumb %>

          <% else %>
            <%= build.label :photo %>
            <%= build.file_field :photo %>
          <% end %>

        </div>
        <%= build.link_to_remove "Remove this Photo" %>
        <% end %>

        <%= f.link_to_add "Add a Photo", :gallery_images %>
        <div class="form-group">
			    <%= f.submit 'Submit', :class => 'btn btn-success' %>
			  </div>

          </fieldset>
        <% end %>
      </div>
     </div>
    </div>

app/views/galleries/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 well">
      <!--vertical Tabs-->
      <div id="verticalTab">
        <ul class="resp-tabs-list">
          <% @tournaments.each do |t| %>

          <% if t.gallery_images.any? %>
            <li><%= t.name %> <%= link_to 'Edit Gallery', edit_gallery_path(t.gallery.id) %></li>
          <% end %>
          
          <% end %>
        </ul>
                    <div class="resp-tabs-container">
                     <% @tournaments.each do |t| %>
                        <div>
                            <div class="clear"></div>
                              <ul class="team-gallery">
                                <% t.gallery_images.each do |g| %>
                                  <li>
                                    <%= link_to image_tag(g.photo.url(:gallery_small), class: 'clb-photo') %> 
                                  </li>
                                <% end %>
                            </ul>
                        </div>
                    <% end %>
                  </div><!--resp-tabs-container-->
                </div><!--/vertical-tab-->



    </div><!--/col-md-12-->
  </div>
</div>

<script type="text/javascript">
            $(document).ready(function() {
                $('#verticalTab').easyResponsiveTabs({
                    type: 'vertical',
                    width: 'auto',
                    fit: true
                });
            });
        </script>
    

app/views/galleries/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 well">
    	<%= nested_form_for @gallery, html: { multipart: true }  do |f| %>
        <fieldset>
        <!-- Form Name -->
        <legend>Create New Gallery</legend>
        
        <div class="form-group">
          <%= f.label :tournament_id  %>
          <%= f.collection_select :tournament_id, Tournament.all, :id, :name, { :prompt => "Please Select a Tournament" }, { class: 'form-control' } %>
        </div>

        <%= f.fields_for :gallery_images do |build| %>

        <div class="form-group">

          <%= build.label :photo %>
          <%= build.file_field :photo %>
        </div>
        <%= build.link_to_remove "Remove this Photo" %>
        <% end %>

        <%= f.link_to_add "Add a Photo", :gallery_images %>
        <div class="form-group">
			    <%= f.submit 'Submit', :class => 'btn btn-success' %>
			  </div>

          </fieldset>
        <% end %>
      </div>
     </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VandalsAdmin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>  
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
    </div>
  <% end %>

  <%= render 'shared/navbar' if user_signed_in? %>

<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Varsity Vandals Admin</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tournaments<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Add Tournament', new_tournament_path %></li>
              <li><%= link_to 'View Tournaments', tournaments_path %></li>
            </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Fixtures<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Add Fixtures', new_fixture_path %></li>
            <li><%= link_to 'View Fixtures', fixtures_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Galleries<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Add Gallery', new_gallery_path %></li>
              <li><%= link_to 'View Galleries', galleries_path %></li>
            </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Logout', destroy_user_session_path, confirm: 'Are you sure you want to Log Out', method: 'delete' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/tournaments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
    	<%= form_for @tournament do |f| %>
        <fieldset>
        <!-- Form Name -->
        <legend>Edit Tournament</legend>

			<!-- Text input-->
			<div class="form-group">
			  <%= f.label :name %>
			  <%= f.text_field :name, class: 'form-control', placeholder: 'Tournament Name' %> 
			</div>

			<!-- Text input-->
			<div class="form-group">
			  <%= f.label :tourn_date %><br>
			  <%= f.date_select :tourn_date, :order => [:day, :month, :year] %>   
			</div>

			<!-- Text input-->
			<div class="form-group">
			  <%= f.label :tourn_location %>
			  <%= f.text_field :tourn_location, class: 'form-control', placeholder: 'Tournament Location' %> 
			</div>

            <div class="form-group">
			  <%= f.submit 'Submit', :class => 'btn btn-success' %>
			</div>

          </fieldset>
        <% end %>
      </div>
     </div>
    </div>

app/views/tournaments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 well">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Tournament Name</th>
              <th>Tournament Location</th>
              <th>Tournament Date</th>
              <th>Options</th>
            </tr>
          </thead>
          <tbody>
          	<% @tournaments.each do |t| %>
          	<tr>
              <td><%= t.name %></td>
              <td><%= t.tourn_location %></td>
              <td><%= date_output(t.tourn_date) %></td>
              <td><%= link_to 'view', tournament_path(t), class: 'btn btn-success' %> <%= link_to 'Edit', edit_tournament_path(t), class: 'btn btn-warning' %> <%= link_to 'Delete', tournament_path(t.id), method: :delete,  :confirm => "Are you sure you want to delete this Tournament?", class: 'btn btn-danger' %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>



    </div>
  </div>
</div>

app/views/tournaments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
    	<%= form_for @tournament do |f| %>
        <fieldset>
        <!-- Form Name -->
        <legend>Create A New Tournament</legend>

			<!-- Text input-->
			<div class="form-group">
			  <%= f.label :name %>
			  <%= f.text_field :name, class: 'form-control', placeholder: 'Tournament Name' %> 
			</div>

			<!-- Text input-->
			<div class="form-group">
			  <%= f.label :tourn_date %><br>
			  <%= f.date_select :tourn_date, :order => [:day, :month, :year] %>   
			</div>

			<!-- Text input-->
			<div class="form-group">
			  <%= f.label :tourn_location %>
			  <%= f.text_field :tourn_location, class: 'form-control', placeholder: 'Tournament Location' %> 
			</div>

            <div class="form-group">
			  <%= f.submit 'Submit', :class => 'btn btn-success' %>
			</div>

          </fieldset>
        <% end %>
      </div>
     </div>
    </div>

app/views/tournaments/show.html.erb
<h1>Tournaments#show</h1>
<p>Find me in app/views/tournaments/show.html.erb</p>